In [1]:
#pandas is a library for working with large datasets and extracting BI from it

import pandas as pd

In [2]:
#read the csv file into a pandas data frame

academy = pd.read_csv('academy_awards.csv')

In [3]:
#show the head of the data frame

academy.head()

   Year                      Category                        Winner
0  1927       Actor in a Leading Role                 Emil Jannings
1  1927     Actress in a Leading Role                  Janet Gaynor
2  1927                Cinematography  Charles Rosher / Karl Struss
3  1927    Directing (Comedy Picture)               Lewis Milestone
4  1927  Directing (Dramatic Picture)                 Frank Borzage

In [4]:
#show the tail of the data frame

academy.tail()

     Year                       Category         Winner
471  1963  Writing (Original Screenplay)  James R. Webb
472  1964        Actor in a Leading Role   Rex Harrison
473  1964     Actor in a Supporting Role  Peter Ustinov
474  1964      Actress in a Leading Role  Julie Andrews
475  1964   Actress in a Supporting Role   Lila Kedrova

In [5]:
#pandas series based on the Category

category = pd.Series(academy['Category'])
category

0            Actor in a Leading Role
1          Actress in a Leading Role
2                     Cinematography
3         Directing (Comedy Picture)
4       Directing (Dramatic Picture)
                   ...
471    Writing (Original Screenplay)
472          Actor in a Leading Role
473       Actor in a Supporting Role
474        Actress in a Leading Role
475     Actress in a Supporting Role
Name: Category, Length: 476, dtype: str

In [6]:
#pandas series based on the Winner

winner = pd.Series(academy['Winner'])
winner

0                     Emil Jannings
1                      Janet Gaynor
2      Charles Rosher / Karl Struss
3                   Lewis Milestone
4                     Frank Borzage
                   ...
471                   James R. Webb
472                    Rex Harrison
473                   Peter Ustinov
474                   Julie Andrews
475                    Lila Kedrova
Name: Winner, Length: 476, dtype: str

In [7]:
#list all the Category values uniquely

category.unique()

<StringArray>
[         'Actor in a Leading Role',        'Actress in a Leading Role',
                   'Cinematography',       'Directing (Comedy Picture)',
     'Directing (Dramatic Picture)',                     'Best Picture',
     'Writing (Adapted Screenplay)',         'Writing (Original Story)',
                    'Art Direction',                        'Directing',
                     'Film Editing',       'Actor in a Supporting Role',
     'Actress in a Supporting Role', 'Cinematography (Black-and-White)',
           'Cinematography (Color)',  'Art Direction (Black-and-White)',
            'Art Direction (Color)',    'Writing (Original Screenplay)',
 'Costume Design (Black-and-White)',           'Costume Design (Color)',
       'International Feature Film',                   'Costume Design']
Length: 22, dtype: str

In [8]:
#count all the winners by values (how many times did someone win the award?)

winner.value_counts()

Winner
John Ford               4
Joseph Ruttenberg       4
Leon Shamroy            4
Joseph L. Mankiewicz    4
Frank Capra             3
                       ..
John Osborne            1
James R. Webb           1
Rex Harrison            1
Julie Andrews           1
Lila Kedrova            1
Name: count, Length: 416, dtype: int64

In [9]:
#data frame for Best Picture

best_picture = academy[academy['Category'] == 'Best Picture']
best_picture

     Year      Category                          Winner
5    1927  Best Picture                           Wings
13   1928  Best Picture             The Broadway Melody
20   1929  Best Picture  All Quiet on the Western Front
27   1930  Best Picture                        Cimarron
35   1931  Best Picture                     Grand Hotel
43   1932  Best Picture                       Cavalcade
52   1934  Best Picture           It Happened One Night
61   1935  Best Picture            Mutiny on the Bounty
72   1936  Best Picture              The Great Ziegfeld
83   1937  Best Picture          The Life of Emile Zola
94   1938  Best Picture      You Can't Take It with You
106  1939  Best Picture              Gone with the Wind
119  1940  Best Picture                         Rebecca
133  1941  Best Picture         How Green Was My Valley
147  1942  Best Picture                    Mrs. Miniver
161  1943  Best Picture                      Casablanca
175  1944  Best Picture                    Going My Way
189  1945  Best Picture                The Lost Weekend
203  1946  Best Picture     The Best Years of Our Lives
217  1947  Best Picture           Gentleman's Agreement
233  1948  Best Picture                          Hamlet
248  1949  Best Picture              All the King's Men
264  1950  Best Picture                   All about Eve
280  1951  Best Picture            An American in Paris
296  1952  Best Picture      The Greatest Show on Earth
312  1953  Best Picture           From Here to Eternity
328  1954  Best Picture               On the Waterfront
344  1955  Best Picture                           Marty
361  1956  Best Picture     Around the World in 80 Days
375  1957  Best Picture    The Bridge on the River Kwai
389  1958  Best Picture                            Gigi
405  1959  Best Picture                         Ben-Hur
421  1960  Best Picture                   The Apartment
437  1961  Best Picture                 West Side Story
453  1962  Best Picture              Lawrence of Arabia
469  1963  Best Picture                       Tom Jones

In [10]:
#data frame for Actor in a Leading Role

leading_actor = academy[academy['Category'] == 'Actor in a Leading Role']
leading_actor

     Year                 Category                         Winner
0    1927  Actor in a Leading Role                  Emil Jannings
8    1928  Actor in a Leading Role                  Warner Baxter
15   1929  Actor in a Leading Role                  George Arliss
22   1930  Actor in a Leading Role               Lionel Barrymore
30   1931  Actor in a Leading Role  Wallace Beery / Fredric March
38   1932  Actor in a Leading Role               Charles Laughton
46   1934  Actor in a Leading Role                    Clark Gable
55   1935  Actor in a Leading Role                Victor McLaglen
64   1936  Actor in a Leading Role                      Paul Muni
75   1937  Actor in a Leading Role                  Spencer Tracy
86   1938  Actor in a Leading Role                  Spencer Tracy
97   1939  Actor in a Leading Role                   Robert Donat
109  1940  Actor in a Leading Role                  James Stewart
123  1941  Actor in a Leading Role                    Gary Cooper
137  1942  Actor in a Leading Role                   James Cagney
151  1943  Actor in a Leading Role                     Paul Lukas
165  1944  Actor in a Leading Role                    Bing Crosby
179  1945  Actor in a Leading Role                    Ray Milland
193  1946  Actor in a Leading Role                  Fredric March
207  1947  Actor in a Leading Role                  Ronald Colman
221  1948  Actor in a Leading Role               Laurence Olivier
236  1949  Actor in a Leading Role             Broderick Crawford
252  1950  Actor in a Leading Role                    José Ferrer
268  1951  Actor in a Leading Role                Humphrey Bogart
284  1952  Actor in a Leading Role                    Gary Cooper
300  1953  Actor in a Leading Role                 William Holden
316  1954  Actor in a Leading Role                  Marlon Brando
332  1955  Actor in a Leading Role                Ernest Borgnine
348  1956  Actor in a Leading Role                    Yul Brynner
365  1957  Actor in a Leading Role                  Alec Guinness
378  1958  Actor in a Leading Role                    David Niven
392  1959  Actor in a Leading Role                Charlton Heston
408  1960  Actor in a Leading Role                 Burt Lancaster
424  1961  Actor in a Leading Role              Maximilian Schell
440  1962  Actor in a Leading Role                   Gregory Peck
456  1963  Actor in a Leading Role                 Sidney Poitier
472  1964  Actor in a Leading Role                   Rex Harrison

In [11]:
#new data frame indexed by Year

academy_by_year = academy.set_index('Year')
academy_by_year

                           Category                        Winner
Year
1927        Actor in a Leading Role                 Emil Jannings
1927      Actress in a Leading Role                  Janet Gaynor
1927                 Cinematography  Charles Rosher / Karl Struss
1927     Directing (Comedy Picture)               Lewis Milestone
1927   Directing (Dramatic Picture)                 Frank Borzage
...                             ...                           ...
1963  Writing (Original Screenplay)                 James R. Webb
1964        Actor in a Leading Role                  Rex Harrison
1964     Actor in a Supporting Role                 Peter Ustinov
1964      Actress in a Leading Role                 Julie Andrews
1964   Actress in a Supporting Role                  Lila Kedrova

[476 rows x 2 columns]

In [12]:
#locate all the winners for 1970

academy_by_year.loc[academy_by_year.index == 1970]

Empty DataFrame
Columns: [Category, Winner]
Index: []

In [13]:
#locate all the winners for 2010

academy_by_year.loc[academy_by_year.index == 2010]

Empty DataFrame
Columns: [Category, Winner]
Index: []

In [14]:
#locate all the winners from 1970 to 2010

academy_by_year.loc[1970:2010]

Empty DataFrame
Columns: [Category, Winner]
Index: []